// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Animal is an autogenerated mock type for the Animal type
type Animal struct {
	mock.Mock
}

// Speak provides a mock function with given fields:
func (_m *Animal) Speak() {
	_m.Called()
}
